### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by jeromesimeon** [sfreytag/friday-theme#1]
Hi *Simon*, I had started using your theme for Jekyll (for a blog I am only just starting). I really love the look and feel and was well along until I realized I couldn't find a clear license for it. Do you have any plan to make your theme open source?

**Comment by sfreytag** [comment]
Hi,

Great! I am glad someone is using it already. Yep, open source. GOod point - I’ll work out a licence and add it to the README. I’ll probably use the same one as Boostrap 4.

cheers,

Simon

**Comment by jeromesimeon** [comment]
Hi Simon. Great, thanks for the quick response!

**Comment by sfreytag** [comment]
License now added - using MIT.

**Comment by jeromesimeon** [comment]
Just thought I'd let you know here. I'm using your theme (with small adjustments). If you're curious the preliminary version is at http://blog.ashortdistanceahead.org

Thank again!

**Comment by sfreytag** [comment]
Cool! Your site is looking great already. I like what you say, 'something fairly minimalistic without being too dry' - that is a really good summary of what I was hoping to achieve. Looks like you've figured out some nice customisations to make it do what you need.
