### ISSUE TITLE
Unknown tag 'link'

### ISSUE THREAD

**Issue by Jeoker** [sfreytag/friday-theme#8]
Hi, I am trying to install this theme on my computer, but it is giving me an error: `jekyll 3.0.1 | Error:  Liquid syntax error: Unknown tag 'link'`
I believe have installed all prerequested things in the tutorial. I didn't find many info about this on the internet. How do I install this tag? Many thanks in advance.

**Comment by Jeoker** [comment]
by the way, I am using windows bash.

**Comment by sfreytag** [comment]
Thanks for trying out friday-theme. I don't yet know of anyone running on Windows, so it would be good to see if we can get it working for you. I do know Jekyll is a bit troublesome on Windows. Have you got a site running with any other themes? I'm using jekyll 3.7.3 - is it feasible to upgrade, your version sounds quite old?

**Comment by sfreytag** [comment]
There's a suggestion here that the link tag was introduced in Jekyll 3.2 ... if you can get up to that version, it might help a lot? https://www.bountysource.com/issues/51385971-failure-on-make-serve-unknown-tag-link

**Comment by Jeoker** [comment]
Oh! thank you for the tips. I finally managed to work it out on ubuntu16.04, it was caused by the version. This is really a neat and nice theme.

And for others who may want to use this theme, I tried `gem update` and `gem update jekyll`, it didn't really help for windows bash, I was still on `jekyll 3.0.1`. So maybe you would like to try something else.

**Comment by sfreytag** [comment]
Great - glad you are up and running.
