### ISSUE TITLE
Will there be scss file?

### ISSUE THREAD

**Issue by mallim** [sfreytag/friday-theme#9]
Hi

This is a great theme which I am currently using.

Will there be scss file for tweaking? I prefer to tweak SCSS file :-)

**Comment by sfreytag** [comment]
Thanks for the feedback! Glad you like it.

This is a bootstrap theme, so the CSS specific to this theme is quite brief. There's just the site.css, which exists to fill in a couple of layout gaps and tweaks where the Bootstrap CSS does not do quite what I want.

You can download the Bootstrap source, which is entirely based on SCSS, and tweak that. When you build it, use your new bootstrap.css in place of the one packaged with this theme.

Does that sound like it will do what you want? If so I will leave this issue open, and use it to remind me to add something to the docs explaining a bit more about how to do it.

**Comment by mallim** [comment]
Thanks for the instruction. Let me try and see :-)

**Comment by sfreytag** [comment]
Good luck! Let me know how you get on...

**Comment by sfreytag** [comment]
I have been increasingly using SCSS with Bootstrap for work, and so have slowly come to realise that your suggestion is a very good one. I am altering the theme now to include the Bootstrap SCSS and some SCSS variables to customise it.
